apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-sync
  namespace: cattle-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-sync
  template:
    metadata:
      labels:
        app: secret-sync
    spec:
      containers:
        - image: registry.k8s.io/pause:3.10
          name: pause
          volumeMounts:
            - mountPath: /mnt/secrets
              name: openbao-secrets
              readOnly: true
      serviceAccountName: secret-sync
      volumes:
        - csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: rancher-secrets
          name: openbao-secrets
