apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: rancher-secrets
  namespace: cattle-system
spec:
  parameters:
    objects: |-
      - objectName: "BOOTSTRAP_PASSWORD"
        secretPath: "secret/data/rancher"
        secretKey: "BOOTSTRAP_PASSWORD"
    roleName: rancher
    vaultAddress: http://openbao.openbao.svc.cluster.local:8200
  provider: openbao
  secretObjects:
    - data:
        - key: BOOTSTRAP_PASSWORD
          objectName: BOOTSTRAP_PASSWORD
      secretName: rancher-bootstrap
      type: Opaque
