// openbao
package openbao

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"openbao.Openbao",
		reflect.TypeOf((*Openbao)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "helm", GoGetter: "Helm"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_Openbao{}
			_jsii_.InitJsiiProxy(&j.Type__constructsConstruct)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoCsi",
		reflect.TypeOf((*OpenbaoCsi)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoCsiAgent",
		reflect.TypeOf((*OpenbaoCsiAgent)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoCsiAgentImage",
		reflect.TypeOf((*OpenbaoCsiAgentImage)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoCsiDaemonSet",
		reflect.TypeOf((*OpenbaoCsiDaemonSet)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoCsiDaemonSetSecurityContext",
		reflect.TypeOf((*OpenbaoCsiDaemonSetSecurityContext)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoCsiDaemonSetUpdateStrategy",
		reflect.TypeOf((*OpenbaoCsiDaemonSetUpdateStrategy)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoCsiImage",
		reflect.TypeOf((*OpenbaoCsiImage)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoCsiLivenessProbe",
		reflect.TypeOf((*OpenbaoCsiLivenessProbe)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoCsiPod",
		reflect.TypeOf((*OpenbaoCsiPod)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoCsiReadinessProbe",
		reflect.TypeOf((*OpenbaoCsiReadinessProbe)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoCsiServiceAccount",
		reflect.TypeOf((*OpenbaoCsiServiceAccount)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoInjector",
		reflect.TypeOf((*OpenbaoInjector)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoInjectorAgentDefaults",
		reflect.TypeOf((*OpenbaoInjectorAgentDefaults)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoInjectorAgentDefaultsTemplateConfig",
		reflect.TypeOf((*OpenbaoInjectorAgentDefaultsTemplateConfig)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoInjectorAgentImage",
		reflect.TypeOf((*OpenbaoInjectorAgentImage)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoInjectorCerts",
		reflect.TypeOf((*OpenbaoInjectorCerts)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoInjectorImage",
		reflect.TypeOf((*OpenbaoInjectorImage)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoInjectorLeaderElector",
		reflect.TypeOf((*OpenbaoInjectorLeaderElector)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoInjectorMetrics",
		reflect.TypeOf((*OpenbaoInjectorMetrics)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoInjectorSecurityContext",
		reflect.TypeOf((*OpenbaoInjectorSecurityContext)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoInjectorService",
		reflect.TypeOf((*OpenbaoInjectorService)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoInjectorServiceAccount",
		reflect.TypeOf((*OpenbaoInjectorServiceAccount)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoInjectorWebhook",
		reflect.TypeOf((*OpenbaoInjectorWebhook)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoProps",
		reflect.TypeOf((*OpenbaoProps)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoServer",
		reflect.TypeOf((*OpenbaoServer)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoServerAuditStorage",
		reflect.TypeOf((*OpenbaoServerAuditStorage)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoServerAuthDelegator",
		reflect.TypeOf((*OpenbaoServerAuthDelegator)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoServerDataStorage",
		reflect.TypeOf((*OpenbaoServerDataStorage)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoServerDev",
		reflect.TypeOf((*OpenbaoServerDev)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoServerHa",
		reflect.TypeOf((*OpenbaoServerHa)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoServerHaDisruptionBudget",
		reflect.TypeOf((*OpenbaoServerHaDisruptionBudget)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoServerHaRaft",
		reflect.TypeOf((*OpenbaoServerHaRaft)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoServerImage",
		reflect.TypeOf((*OpenbaoServerImage)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoServerIngress",
		reflect.TypeOf((*OpenbaoServerIngress)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoServerIngressHosts",
		reflect.TypeOf((*OpenbaoServerIngressHosts)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoServerLivenessProbe",
		reflect.TypeOf((*OpenbaoServerLivenessProbe)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoServerNetworkPolicy",
		reflect.TypeOf((*OpenbaoServerNetworkPolicy)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoServerPersistentVolumeClaimRetentionPolicy",
		reflect.TypeOf((*OpenbaoServerPersistentVolumeClaimRetentionPolicy)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoServerReadinessProbe",
		reflect.TypeOf((*OpenbaoServerReadinessProbe)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoServerRoute",
		reflect.TypeOf((*OpenbaoServerRoute)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoServerService",
		reflect.TypeOf((*OpenbaoServerService)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoServerServiceAccount",
		reflect.TypeOf((*OpenbaoServerServiceAccount)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoServerServiceAccountServiceDiscovery",
		reflect.TypeOf((*OpenbaoServerServiceAccountServiceDiscovery)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoServerServiceActive",
		reflect.TypeOf((*OpenbaoServerServiceActive)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoServerServiceInstanceSelector",
		reflect.TypeOf((*OpenbaoServerServiceInstanceSelector)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoServerServiceStandby",
		reflect.TypeOf((*OpenbaoServerServiceStandby)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoServerStandalone",
		reflect.TypeOf((*OpenbaoServerStandalone)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoServerStatefulSet",
		reflect.TypeOf((*OpenbaoServerStatefulSet)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoServerStatefulSetSecurityContext",
		reflect.TypeOf((*OpenbaoServerStatefulSetSecurityContext)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoServerTelemetry",
		reflect.TypeOf((*OpenbaoServerTelemetry)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoServerTelemetryPrometheusRules",
		reflect.TypeOf((*OpenbaoServerTelemetryPrometheusRules)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoUi",
		reflect.TypeOf((*OpenbaoUi)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"openbao.OpenbaoValues",
		reflect.TypeOf((*OpenbaoValues)(nil)).Elem(),
	)
}
