apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: openbao
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: openbao-csi-provider
    helm.sh/chart: openbao-0.28.3
  name: openbao-csi-provider-agent-config
  namespace: openbao
data:
  config.hcl: |
    vault {
        "address" = "http://openbao.openbao.svc:8200"
    }

    cache {}

    listener "unix" {
        address = "/var/run/vault/agent.sock"
        tls_disable = true
    }
