apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbird-peer
  namespace: netbird
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netbird-peer
  template:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        app: netbird-peer
    spec:
      containers:
        - env:
            - name: NB_SETUP_KEY
              valueFrom:
                secretKeyRef:
                  key: NETBIRD_SETUP_KEY
                  name: netbird-setup-key
            - name: NB_MANAGEMENT_URL
              value: https://netbird.madhan.app
            - name: NB_HOSTNAME
              value: k8s-routing-peer
          image: netbirdio/netbird:0.66.2
          name: netbird
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
            privileged: true
          volumeMounts:
            - mountPath: /mnt/secrets
              name: openbao-secrets
              readOnly: true
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      volumes:
        - csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: netbird-secrets
          name: openbao-secrets
