apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: netbird-secrets
  namespace: netbird
spec:
  parameters:
    objects: |-
      - objectName: "NETBIRD_SETUP_KEY"
        secretPath: "secret/data/netbird"
        secretKey: "NETBIRD_SETUP_KEY"
    roleName: netbird
    vaultAddress: http://openbao.openbao.svc.cluster.local:8200
  provider: openbao
  secretObjects:
    - data:
        - key: NETBIRD_SETUP_KEY
          objectName: NETBIRD_SETUP_KEY
      secretName: netbird-setup-key
      type: Opaque
