apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: netbird-peer
  namespace: netbird
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netbird-peer
  serviceName: netbird-peer
  template:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        app: netbird-peer
    spec:
      containers:
        - env:
            - name: NB_SETUP_KEY
              valueFrom:
                secretKeyRef:
                  key: NETBIRD_SETUP_KEY
                  name: netbird-setup-key
            - name: NB_MANAGEMENT_URL
              value: https://netbird.madhan.app
            - name: NB_HOSTNAME
              value: k8s-routing-peer
          image: netbirdio/netbird:0.71.4
          name: netbird
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
            privileged: true
          volumeMounts:
            - mountPath: /var/lib/netbird
              name: netbird-config
            - mountPath: /mnt/secrets
              name: openbao-secrets
              readOnly: true
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      initContainers:
        - args:
            - -c
            - iptables -t nat -C POSTROUTING -s 100.109.0.0/16 -d 192.168.1.0/24 -j MASQUERADE 2>/dev/null || iptables -t nat -A POSTROUTING -s 100.109.0.0/16 -d 192.168.1.0/24 -j MASQUERADE
          command:
            - /bin/sh
          image: netbirdio/netbird:0.71.4
          name: setup-iptables
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            privileged: true
      nodeSelector:
        kubernetes.io/hostname: k8s-worker1
      volumes:
        - csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: netbird-secrets
          name: openbao-secrets
  volumeClaimTemplates:
    - metadata:
        name: netbird-config
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
