apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: n8n-secrets
  namespace: n8n
spec:
  parameters:
    objects: |-
      - objectName: "DB_PASSWORD"
        secretPath: "secret/data/n8n"
        secretKey: "DB_PASSWORD"
      - objectName: "ENCRYPTION_KEY"
        secretPath: "secret/data/n8n"
        secretKey: "ENCRYPTION_KEY"
    roleName: n8n
    vaultAddress: http://openbao.openbao.svc.cluster.local:8200
  provider: openbao
  secretObjects:
    - data:
        - key: DB_PASSWORD
          objectName: DB_PASSWORD
        - key: N8N_ENCRYPTION_KEY
          objectName: ENCRYPTION_KEY
      secretName: n8n-secrets
      type: Opaque
