apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: headlamp-readonly
  name: headlamp-readonly-token
  namespace: headlamp
type: kubernetes.io/service-account-token
