apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: nvidia-device-plugin
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: node-feature-discovery
    app.kubernetes.io/version: v0.17.3
    helm.sh/chart: nfd-0.17.3
  name: nvidia-device-plugin-node-feature-discovery-master-conf
  namespace: nvidia-gpu-operator
data:
  nfd-master.conf: |-
    extraLabelNs:
    - nvidia.com
