apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/instance: nvidia-device-plugin
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nvidia-device-plugin
    app.kubernetes.io/version: 0.18.2
    helm.sh/chart: nvidia-device-plugin-0.18.2
  name: nvidia-device-plugin
  namespace: nvidia-gpu-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: nvidia-device-plugin
      app.kubernetes.io/name: nvidia-device-plugin
  template:
    metadata:
      annotations:
        checksum/config: 8ff6bec6ce62cff6ba5625f16df2d200b948082a82358404915fc2a4fc67ff61
      labels:
        app.kubernetes.io/instance: nvidia-device-plugin
        app.kubernetes.io/name: nvidia-device-plugin
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: feature.node.kubernetes.io/pci-10de.present
                    operator: In
                    values:
                      - "true"
              - matchExpressions:
                  - key: feature.node.kubernetes.io/cpu-model.vendor_id
                    operator: In
                    values:
                      - NVIDIA
              - matchExpressions:
                  - key: nvidia.com/gpu.present
                    operator: In
                    values:
                      - "true"
      containers:
        - command:
            - config-manager
          env:
            - name: ONESHOT
              value: "false"
            - name: KUBECONFIG
              value: ""
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_LABEL
              value: nvidia.com/device-plugin.config
            - name: CONFIG_FILE_SRCDIR
              value: /available-configs
            - name: CONFIG_FILE_DST
              value: /config/config.yaml
            - name: DEFAULT_CONFIG
              value: default
            - name: FALLBACK_STRATEGIES
              value: named,single
            - name: SEND_SIGNAL
              value: "true"
            - name: SIGNAL
              value: "1"
            - name: PROCESS_TO_SIGNAL
              value: nvidia-device-plugin
          image: nvcr.io/nvidia/k8s-device-plugin:v0.18.2
          name: nvidia-device-plugin-sidecar
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
          volumeMounts:
            - mountPath: /available-configs
              name: available-configs
            - mountPath: /config
              name: config
        - command:
            - nvidia-device-plugin
          env:
            - name: MPS_ROOT
              value: /run/nvidia/mps
            - name: CONFIG_FILE
              value: /config/config.yaml
            - name: NVIDIA_MIG_MONITOR_DEVICES
              value: all
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: compute,utility
          image: nvcr.io/nvidia/k8s-device-plugin:v0.18.2
          imagePullPolicy: IfNotPresent
          name: nvidia-device-plugin-ctr
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
          volumeMounts:
            - mountPath: /var/lib/kubelet/device-plugins
              name: kubelet-device-plugins-dir
            - mountPath: /dev/shm
              name: mps-shm
            - mountPath: /mps
              name: mps-root
            - mountPath: /var/run/cdi
              name: cdi-root
            - mountPath: /available-configs
              name: available-configs
            - mountPath: /config
              name: config
      initContainers:
        - command:
            - config-manager
          env:
            - name: ONESHOT
              value: "true"
            - name: KUBECONFIG
              value: ""
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_LABEL
              value: nvidia.com/device-plugin.config
            - name: CONFIG_FILE_SRCDIR
              value: /available-configs
            - name: CONFIG_FILE_DST
              value: /config/config.yaml
            - name: DEFAULT_CONFIG
              value: default
            - name: FALLBACK_STRATEGIES
              value: named,single
            - name: SEND_SIGNAL
              value: "false"
            - name: SIGNAL
              value: ""
            - name: PROCESS_TO_SIGNAL
              value: ""
          image: nvcr.io/nvidia/k8s-device-plugin:v0.18.2
          name: nvidia-device-plugin-init
          volumeMounts:
            - mountPath: /available-configs
              name: available-configs
            - mountPath: /config
              name: config
      priorityClassName: system-node-critical
      securityContext: {}
      serviceAccountName: nvidia-device-plugin-service-account
      shareProcessNamespace: true
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Exists
      volumes:
        - hostPath:
            path: /var/lib/kubelet/device-plugins
            type: Directory
          name: kubelet-device-plugins-dir
        - hostPath:
            path: /run/nvidia/mps
            type: DirectoryOrCreate
          name: mps-root
        - hostPath:
            path: /run/nvidia/mps/shm
          name: mps-shm
        - hostPath:
            path: /var/run/cdi
            type: DirectoryOrCreate
          name: cdi-root
        - configMap:
            name: nvidia-device-plugin-configs
          name: available-configs
        - emptyDir: {}
          name: config
  updateStrategy:
    type: RollingUpdate
