apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/instance: nvidia-device-plugin
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nvidia-device-plugin
    app.kubernetes.io/version: 0.18.2
    helm.sh/chart: nvidia-device-plugin-0.18.2
  name: nvidia-device-plugin-gpu-feature-discovery
  namespace: nvidia-gpu-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: nvidia-device-plugin
      app.kubernetes.io/name: nvidia-device-plugin
  template:
    metadata:
      annotations:
        checksum/config: 5ffda4fe5658197ec89ac0f74a9135727dfec83b6228b4f48264f1da7c67adc5
      labels:
        app.kubernetes.io/instance: nvidia-device-plugin
        app.kubernetes.io/name: nvidia-device-plugin
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: feature.node.kubernetes.io/pci-10de.present
                    operator: In
                    values:
                      - "true"
              - matchExpressions:
                  - key: feature.node.kubernetes.io/cpu-model.vendor_id
                    operator: In
                    values:
                      - NVIDIA
              - matchExpressions:
                  - key: nvidia.com/gpu.present
                    operator: In
                    values:
                      - "true"
      containers:
        - command:
            - config-manager
          env:
            - name: ONESHOT
              value: "false"
            - name: KUBECONFIG
              value: ""
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_LABEL
              value: nvidia.com/device-plugin.config
            - name: CONFIG_FILE_SRCDIR
              value: /available-configs
            - name: CONFIG_FILE_DST
              value: /config/config.yaml
            - name: DEFAULT_CONFIG
              value: default
            - name: FALLBACK_STRATEGIES
              value: named,single
            - name: SEND_SIGNAL
              value: "true"
            - name: SIGNAL
              value: "1"
            - name: PROCESS_TO_SIGNAL
              value: gpu-feature-discovery
          image: nvcr.io/nvidia/k8s-device-plugin:v0.18.2
          name: gpu-feature-discovery-sidecar
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /available-configs
              name: available-configs
            - mountPath: /config
              name: config
        - command:
            - gpu-feature-discovery
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: GFD_USE_NODE_FEATURE_API
              value: "false"
            - name: CONFIG_FILE
              value: /config/config.yaml
            - name: NVIDIA_MIG_MONITOR_DEVICES
              value: all
          image: nvcr.io/nvidia/k8s-device-plugin:v0.18.2
          imagePullPolicy: IfNotPresent
          name: gpu-feature-discovery-ctr
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /etc/kubernetes/node-feature-discovery/features.d
              name: output-dir
            - mountPath: /sys
              name: host-sys
            - mountPath: /available-configs
              name: available-configs
            - mountPath: /config
              name: config
      initContainers:
        - command:
            - config-manager
          env:
            - name: ONESHOT
              value: "true"
            - name: KUBECONFIG
              value: ""
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_LABEL
              value: nvidia.com/device-plugin.config
            - name: CONFIG_FILE_SRCDIR
              value: /available-configs
            - name: CONFIG_FILE_DST
              value: /config/config.yaml
            - name: DEFAULT_CONFIG
              value: default
            - name: FALLBACK_STRATEGIES
              value: named,single
            - name: SEND_SIGNAL
              value: "false"
            - name: SIGNAL
              value: ""
            - name: PROCESS_TO_SIGNAL
              value: ""
          image: nvcr.io/nvidia/k8s-device-plugin:v0.18.2
          name: gpu-feature-discovery-init
          volumeMounts:
            - mountPath: /available-configs
              name: available-configs
            - mountPath: /config
              name: config
      priorityClassName: system-node-critical
      securityContext: {}
      serviceAccountName: nvidia-device-plugin-service-account
      shareProcessNamespace: true
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Exists
      volumes:
        - hostPath:
            path: /etc/kubernetes/node-feature-discovery/features.d
            type: DirectoryOrCreate
          name: output-dir
        - hostPath:
            path: /sys
            type: Directory
          name: host-sys
        - hostPath:
            path: /
            type: Directory
          name: driver-root
        - configMap:
            name: nvidia-device-plugin-configs
          name: available-configs
        - emptyDir: {}
          name: config
  updateStrategy:
    type: RollingUpdate
