apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: dcgm-exporter
    app.kubernetes.io/instance: dcgm-exporter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dcgm-exporter
    app.kubernetes.io/version: 4.8.2
    helm.sh/chart: dcgm-exporter-4.8.2
  name: dcgm-exporter
  namespace: nvidia-gpu-operator
spec:
  internalTrafficPolicy: Cluster
  ports:
    - name: metrics
      port: 9400
      protocol: TCP
      targetPort: 9400
  selector:
    app.kubernetes.io/component: dcgm-exporter
    app.kubernetes.io/instance: dcgm-exporter
    app.kubernetes.io/name: dcgm-exporter
  type: ClusterIP
