apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: dcgm-exporter
    app.kubernetes.io/instance: dcgm-exporter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dcgm-exporter
    app.kubernetes.io/version: 3.4.2
    helm.sh/chart: dcgm-exporter-3.4.2
  name: dcgm-exporter
  namespace: nvidia-gpu-operator
spec:
  endpoints:
    - honorLabels: false
      interval: 15s
      path: /metrics
      port: metrics
      relabelings: []
  namespaceSelector:
    matchNames:
      - nvidia-gpu-operator
  selector:
    matchLabels:
      app.kubernetes.io/component: dcgm-exporter
      app.kubernetes.io/instance: dcgm-exporter
      app.kubernetes.io/name: dcgm-exporter
