apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: dcgm-exporter
    app.kubernetes.io/instance: dcgm-exporter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dcgm-exporter
    app.kubernetes.io/version: 4.8.2
    helm.sh/chart: dcgm-exporter-4.8.2
  name: dcgm-exporter
  namespace: nvidia-gpu-operator
automountServiceAccountToken: false
