apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
    helm.sh/hook-weight: "20"
  labels:
    app: secrets-store-csi-driver
    app.kubernetes.io/instance: secrets-store-csi-driver
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: secrets-store-csi-driver
    app.kubernetes.io/version: 1.5.6
    helm.sh/chart: secrets-store-csi-driver-1.5.6
  name: secrets-store-csi-driver-keep-crds
  namespace: kube-system
spec:
  backoffLimit: 3
  template:
    metadata:
      name: secrets-store-csi-driver-keep-crds
    spec:
      containers:
        - args:
            - patch
            - crd
            - secretproviderclasses.secrets-store.csi.x-k8s.io
            - secretproviderclasspodstatuses.secrets-store.csi.x-k8s.io
            - -p
            - '{"metadata":{"annotations": {"helm.sh/resource-policy": "keep"}}}'
          image: registry.k8s.io/csi-secrets-store/driver-crds:v1.5.6
          imagePullPolicy: IfNotPresent
          name: crds-keep
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Never
      serviceAccountName: secrets-store-csi-driver-keep-crds
      tolerations:
        - operator: Exists
