apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
    helm.sh/hook-weight: "10"
  labels:
    app: secrets-store-csi-driver
    app.kubernetes.io/instance: secrets-store-csi-driver
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: secrets-store-csi-driver
    app.kubernetes.io/version: 1.5.6
    helm.sh/chart: secrets-store-csi-driver-1.5.6
  name: secrets-store-csi-driver-upgrade-crds
  namespace: kube-system
spec:
  backoffLimit: 3
  template:
    metadata:
      name: secrets-store-csi-driver-upgrade-crds
    spec:
      containers:
        - args:
            - apply
            - -f
            - crds/
          image: registry.k8s.io/csi-secrets-store/driver-crds:v1.5.6
          imagePullPolicy: IfNotPresent
          name: crds-upgrade
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Never
      serviceAccountName: secrets-store-csi-driver-upgrade-crds
      tolerations:
        - operator: Exists
