apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: secrets-store-csi-driver
    app.kubernetes.io/instance: secrets-store-csi-driver
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: secrets-store-csi-driver
    app.kubernetes.io/version: 1.5.6
    helm.sh/chart: secrets-store-csi-driver-1.5.6
  name: secrets-store-csi-driver
  namespace: kube-system
