apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: grafana-secrets
  namespace: grafana
spec:
  parameters:
    objects: |-
      - objectName: "ADMIN_PASSWORD"
        secretPath: "secret/data/grafana"
        secretKey: "ADMIN_PASSWORD"
    roleName: grafana
    vaultAddress: http://openbao.openbao.svc.cluster.local:8200
  provider: openbao
