apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: grafana-secrets
  namespace: grafana
spec:
  parameters:
    objects: |-
      - objectName: "ADMIN_PASSWORD"
        secretPath: "secret/data/grafana"
        secretKey: "ADMIN_PASSWORD"
      - objectName: "OAUTH_CLIENT_SECRET"
        secretPath: "secret/data/grafana"
        secretKey: "OAUTH_CLIENT_SECRET"
    roleName: grafana
    vaultAddress: http://openbao.openbao.svc.cluster.local:8200
  provider: openbao
  secretObjects:
    - data:
        - key: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
          objectName: OAUTH_CLIENT_SECRET
      secretName: grafana-oauth-secret
      type: Opaque
