apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: core
    app.kubernetes.io/instance: falco
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: falcosidekick
    app.kubernetes.io/part-of: falcosidekick
    app.kubernetes.io/version: 2.31.1
    helm.sh/chart: falcosidekick-0.12.1
  name: falco-falcosidekick
  namespace: falco
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: falco-falcosidekick
subjects:
  - kind: ServiceAccount
    name: falco-falcosidekick
