apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: infisical-opera-controller-manager
  name: infisical-opera-controller-manager-token
  namespace: infisical
type: kubernetes.io/service-account-token
