apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=false
  name: harbor-secrets
  namespace: harbor
spec:
  authentication:
    kubernetesAuth:
      identityId: 47aef6c1-bdeb-40fa-be46-63bbcfe6a4df
      secretsScope:
        envSlug: prod
        projectSlug: homelab-prod
        secretsPath: /harbor
      serviceAccountRef:
        name: infisical-opera-controller-manager
        namespace: infisical
  hostAPI: http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080
  managedSecretReference:
    creationPolicy: Owner
    secretName: harbor-admin
    secretNamespace: harbor
  resyncInterval: 60
