apiVersion: v1
kind: Secret
metadata:
  labels:
    app: harbor
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: harbor
    app.kubernetes.io/part-of: harbor
    app.kubernetes.io/version: 2.15.2
    chart: harbor
    heritage: Helm
    release: harbor
  name: harbor-registry-htpasswd
  namespace: harbor
data:
  REGISTRY_HTPASSWD: aGFyYm9yX3JlZ2lzdHJ5X3VzZXI6JDJhJDEwJE9KcFkyS09LeWx5OEhDc0k4aEo5Y096N2tpSnZzUVgzTU9kaDFnWTk3cWYwM1lvZGxzQmV5
type: Opaque
