apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: harbor-secrets
  namespace: harbor
spec:
  parameters:
    objects: |-
      - objectName: "HARBOR_ADMIN_PASSWORD"
        secretPath: "secret/data/harbor"
        secretKey: "HARBOR_ADMIN_PASSWORD"
    roleName: harbor
    vaultAddress: http://openbao.openbao.svc.cluster.local:8200
  provider: openbao
  secretObjects:
    - data:
        - key: HARBOR_ADMIN_PASSWORD
          objectName: HARBOR_ADMIN_PASSWORD
      secretName: harbor-admin
      type: Opaque
