package cloud

import (
	"github.com/madhank93/homelab/core/internal/cfg"
	"fmt"
	"os"

	cf "github.com/pulumi/pulumi-cloudflare/sdk/v5/go/cloudflare"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// publicServices lists services exposed to the public internet via the Hetzner VPS.
// Each entry creates an A record pointing to the VPS IP and a Traefik router in
// public-services.yml (generated by generateTraefikPublicServices in hetzner_vps.go).
// To make a service LAN-only: remove it from this list — DNS falls back to the wildcard.
var publicServices = []string{"grafana", "harbor"}

// ManageCloudflare manages Cloudflare DNS records for the homelab.
func ManageCloudflare(ctx *pulumi.Context) error {
	var hetznerCfg HetznerConfig
	if err := cfg.Load("hetzner", &hetznerCfg); err != nil {
		return err
	}
	hetznerIP := hetznerCfg.VpsIP
	if hetznerIP == "" {
		return fmt.Errorf("hetzner.vps_ip not set in config.yml")
	}

	cfToken := os.Getenv("CLOUDFLARE_API_TOKEN")
	if cfToken == "" {
		return fmt.Errorf("CLOUDFLARE_API_TOKEN not in environment")
	}

	provider, err := cf.NewProvider(ctx, "cloudflare", &cf.ProviderArgs{
		ApiToken: pulumi.String(cfToken),
	})
	if err != nil {
		return err
	}

	zoneID := "ab8d029e91fb2bb38cb8bc91b9f0b218"

	newRecord := func(name, logicalName, ip, comment string) error {
		_, err := cf.NewRecord(ctx, logicalName, &cf.RecordArgs{
			ZoneId:  pulumi.String(zoneID),
			Name:    pulumi.String(name),
			Type:    pulumi.String("A"),
			Content: pulumi.String(ip),
			Ttl:     pulumi.Int(1),
			Proxied: pulumi.Bool(false),
			Comment: pulumi.StringPtr(comment),
		}, pulumi.Provider(provider))
		return err
	}

	// Wildcard — all *.madhan.app defaults to LAN gateway (private, no internet)
	if err := newRecord("*", "wildcard-madhan-app", "192.168.1.220", "Homelab wildcard - LAN gateway"); err != nil {
		return err
	}

	// Always-public: Authentik, NetBird, NetBird expose base
	for _, svc := range []string{"auth", "netbird", "proxy"} {
		if err := newRecord(svc+".madhan.app", "always-public-"+svc, hetznerIP, "Bifrost VPS - always public"); err != nil {
			return err
		}
	}

	// Wildcard for NetBird expose feature
	if err := newRecord("*.proxy.madhan.app", "wildcard-proxy-madhan-app", hetznerIP, "NetBird expose wildcard"); err != nil {
		return err
	}

	// Selectively public homelab services — edit publicServices slice to toggle
	for _, svc := range publicServices {
		if err := newRecord(svc+".madhan.app", "public-svc-"+svc, hetznerIP, "Public via Bifrost+Authentik SSO"); err != nil {
			return err
		}
	}

	return nil
}
