apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: vmagent
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-metrics-agent
    app.kubernetes.io/version: v1.108.1
    helm.sh/chart: victoria-metrics-agent-0.15.3
  name: vmagent-victoria-metrics-agent
  namespace: victoria-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: vmagent
      app.kubernetes.io/name: victoria-metrics-agent
  template:
    metadata:
      annotations:
        checksum/config: ee4f6a72dbd3c579082331304e8dcf497977c2cd6b34cc1d483b1152c430a5e4
      labels:
        app.kubernetes.io/instance: vmagent
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: victoria-metrics-agent
    spec:
      containers:
        - args:
            - --envflag.enable
            - --envflag.prefix=VM_
            - --httpListenAddr=:8429
            - --loggerFormat=json
            - --promscrape.config=/config/scrape/scrape.yml
            - --remoteWrite.tmpDataPath=/tmpData
            - --remoteWrite.url=http://victoria-metrics-victoria-metrics-cluster-vminsert.victoria-metrics.svc.cluster.local:8480/insert/0/prometheus/api/v1/write
          image: victoriametrics/vmagent:v1.108.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 15
            tcpSocket:
              port: http
            timeoutSeconds: 5
          name: vmagent
          ports:
            - containerPort: 8429
              name: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext: {}
          volumeMounts:
            - mountPath: /tmpData
              name: tmpdata
            - mountPath: /config/scrape
              name: scrape-config
            - mountPath: /config/rw
              name: rw-config
          workingDir: /
      securityContext: {}
      serviceAccountName: vmagent-victoria-metrics-agent
      tolerations:
        - operator: Exists
      volumes:
        - emptyDir: {}
          name: tmpdata
        - configMap:
            name: vmagent-victoria-metrics-agent-rw
          name: rw-config
        - configMap:
            name: vmagent-victoria-metrics-agent-config
          name: scrape-config
