apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: vmagent
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-metrics-agent
    app.kubernetes.io/version: v1.108.1
    helm.sh/chart: victoria-metrics-agent-0.15.3
  name: vmagent-victoria-metrics-agent
  namespace: victoria-metrics
