apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  labels:
    app.kubernetes.io/component: victoria-metrics-k8s-stack-vmagent
    app.kubernetes.io/instance: victoria-metrics
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-metrics-k8s-stack
    app.kubernetes.io/version: v1.137.0
    helm.sh/chart: victoria-metrics-k8s-stack-0.72.4
  name: vm-stack
  namespace: victoria-metrics
spec:
  externalLabels: {}
  extraArgs:
    promscrape.dropOriginalLabels: "true"
    promscrape.streamParse: "true"
  image:
    tag: v1.137.0
  inlineScrapeConfig: |
    - job_name: "openbao"
      static_configs:
        - targets: ["openbao.openbao.svc.cluster.local:8200"]
      metrics_path: /v1/sys/metrics
      params:
        format: [prometheus]
  license: {}
  port: "8429"
  remoteWrite:
    - url: http://vmsingle-vm-stack.victoria-metrics.svc.cluster.local.:8428/api/v1/write
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  scrapeInterval: 30s
  selectAllByDefault: true
  tolerations:
    - operator: Exists
