apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  labels:
    app.kubernetes.io/component: victoria-metrics-k8s-stack-vmsingle
    app.kubernetes.io/instance: victoria-metrics
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-metrics-k8s-stack
    app.kubernetes.io/version: v1.137.0
    helm.sh/chart: victoria-metrics-k8s-stack-0.72.4
  name: victoria-metrics-victoria-metrics-k8s-stack
  namespace: victoria-metrics
spec:
  extraArgs:
    vmalert.proxyURL: http://vmalert-victoria-metrics-victoria-metrics-k8s-stack.victoria-metrics.svc.cluster.local.:8080
  image:
    tag: v1.137.0
  license: {}
  port: "8428"
  replicaCount: 1
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 512Mi
  retentionPeriod: 30d
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 100Gi
