apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow
  namespace: argocd
spec:
  destination:
    namespace: kubeflow
    server: https://kubernetes.default.svc
  project: default
  source:
    path: workloads/ai/kubeflow
    repoURL: https://github.com/madhank93/homelab.git
    targetRevision: v0.1.5
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
