apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: notebook-gateway-controller
  namespace: kubeflow
rules:
  - apiGroups:
      - kubeflow.org
    resources:
      - notebooks
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - tensorboard.kubeflow.org
    resources:
      - tensorboards
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - httproutes
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - referencegrants
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - delete
