apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: ollama
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ollama
    app.kubernetes.io/version: 0.24.0
    helm.sh/chart: ollama-1.57.0
  name: ollama
  namespace: ollama
automountServiceAccountToken: true
