// cert-manager
package certmanager

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"cert-manager.Certmanager",
		reflect.TypeOf((*Certmanager)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "helm", GoGetter: "Helm"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_Certmanager{}
			_jsii_.InitJsiiProxy(&j.Type__constructsConstruct)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"cert-manager.CertmanagerProps",
		reflect.TypeOf((*CertmanagerProps)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"cert-manager.HelmValues",
		reflect.TypeOf((*HelmValues)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"cert-manager.HelmValuesAcmesolver",
		reflect.TypeOf((*HelmValuesAcmesolver)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"cert-manager.HelmValuesAcmesolverImage",
		reflect.TypeOf((*HelmValuesAcmesolverImage)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"cert-manager.HelmValuesCainjector",
		reflect.TypeOf((*HelmValuesCainjector)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"cert-manager.HelmValuesCainjectorImage",
		reflect.TypeOf((*HelmValuesCainjectorImage)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"cert-manager.HelmValuesCainjectorPodDisruptionBudget",
		reflect.TypeOf((*HelmValuesCainjectorPodDisruptionBudget)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"cert-manager.HelmValuesCainjectorServiceAccount",
		reflect.TypeOf((*HelmValuesCainjectorServiceAccount)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"cert-manager.HelmValuesCrds",
		reflect.TypeOf((*HelmValuesCrds)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"cert-manager.HelmValuesGlobal",
		reflect.TypeOf((*HelmValuesGlobal)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"cert-manager.HelmValuesGlobalLeaderElection",
		reflect.TypeOf((*HelmValuesGlobalLeaderElection)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"cert-manager.HelmValuesGlobalPodSecurityPolicy",
		reflect.TypeOf((*HelmValuesGlobalPodSecurityPolicy)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"cert-manager.HelmValuesGlobalRbac",
		reflect.TypeOf((*HelmValuesGlobalRbac)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"cert-manager.HelmValuesImage",
		reflect.TypeOf((*HelmValuesImage)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"cert-manager.HelmValuesIngressShim",
		reflect.TypeOf((*HelmValuesIngressShim)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"cert-manager.HelmValuesPodDisruptionBudget",
		reflect.TypeOf((*HelmValuesPodDisruptionBudget)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"cert-manager.HelmValuesPrometheus",
		reflect.TypeOf((*HelmValuesPrometheus)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"cert-manager.HelmValuesPrometheusPodmonitor",
		reflect.TypeOf((*HelmValuesPrometheusPodmonitor)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"cert-manager.HelmValuesPrometheusServicemonitor",
		reflect.TypeOf((*HelmValuesPrometheusServicemonitor)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"cert-manager.HelmValuesServiceAccount",
		reflect.TypeOf((*HelmValuesServiceAccount)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"cert-manager.HelmValuesStartupapicheck",
		reflect.TypeOf((*HelmValuesStartupapicheck)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"cert-manager.HelmValuesStartupapicheckImage",
		reflect.TypeOf((*HelmValuesStartupapicheckImage)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"cert-manager.HelmValuesStartupapicheckRbac",
		reflect.TypeOf((*HelmValuesStartupapicheckRbac)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"cert-manager.HelmValuesStartupapicheckServiceAccount",
		reflect.TypeOf((*HelmValuesStartupapicheckServiceAccount)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"cert-manager.HelmValuesWebhook",
		reflect.TypeOf((*HelmValuesWebhook)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"cert-manager.HelmValuesWebhookImage",
		reflect.TypeOf((*HelmValuesWebhookImage)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"cert-manager.HelmValuesWebhookMutatingWebhookConfiguration",
		reflect.TypeOf((*HelmValuesWebhookMutatingWebhookConfiguration)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"cert-manager.HelmValuesWebhookNetworkPolicy",
		reflect.TypeOf((*HelmValuesWebhookNetworkPolicy)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"cert-manager.HelmValuesWebhookPodDisruptionBudget",
		reflect.TypeOf((*HelmValuesWebhookPodDisruptionBudget)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"cert-manager.HelmValuesWebhookServiceAccount",
		reflect.TypeOf((*HelmValuesWebhookServiceAccount)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"cert-manager.HelmValuesWebhookValidatingWebhookConfiguration",
		reflect.TypeOf((*HelmValuesWebhookValidatingWebhookConfiguration)(nil)).Elem(),
	)
}
